# Generated by Django 4.2.5 on 2024-04-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('request_user_password_reset_token', 'Can request user password reset token')]},
        ),
    ]
